#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

source $SCRIPT_DIR/params.conf

source $USER_CONF_FILE
source $MACHINES_CONF_FILE

create_ssh_keys() {
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY_PATH" -N ""
}

delete_ssh_key_from_remote() {
    source $SCRIPT_DIR/develop_getMachines > /dev/null
    local name="$1"
    local ip_port="${REMOTE_MACHINES[$name]}"

    if [[ -z "$ip_port" ]]; then
        echo "Máquina [$name] no encontrada"
        return 1   
    fi

    local ip="${ip_port%%:*}"
    local port="${ip_port##*:}"
    key_content="$(< "$SSH_PUBKEY_PATH")"

    ssh -i $SSH_KEY_PATH -p $port $USER@$ip <<EOF
if [[ -f ~/.ssh/authorized_keys ]]; then
    # Hacer backup
    cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.bak

    # Filtrar línea exacta de la clave
    grep -vF "$key_content" ~/.ssh/authorized_keys.bak > ~/.ssh/authorized_keys

    # Corregir permisos
    chmod 600 ~/.ssh/authorized_keys
    echo "Clave eliminada (si estaba presente)"
else
    echo "No existe ~/.ssh/authorized_keys"
fi
EOF

}

setup_ssh_access() {
    check_ssh_keys
    local name="$1"
    local ip_port="${REMOTE_MACHINES[$name]}"   #Se ejecuta en un proceso en el que esta definido

    if [[ -z "$ip_port" ]]; then
        echo "Máquina [$name] no encontrada"
        continue
    fi

    local ip="${ip_port%%:*}"
    local port="${ip_port##*:}"

    #echo "Verificando acceso SSH a [$name] => [$ip:$port]..."

    # Intentar conectar sin contraseña (timeout corto)
    ssh -q -o BatchMode=yes -o ConnectTimeout=5 -p "$port" "$USER@$ip" 'exit' 2>/dev/null

    if [[ $? -ne 0 ]]; then
        echo "Acceso no configurado para [$name], copiando clave pública..."

        # Intenta copiar clave pública
        ssh-copy-id -i $SSH_PUBKEY_PATH -p "$port" "$USER@$ip" 2>/dev/null

        # Establecer permisos adecuados
        ssh -i $SSH_KEY_PATH -p $port "$USER@$ip" <<'EOF'
        sudo chmod 700 ~/.ssh
        sudo chmod 600 ~/.ssh/authorized_keys
EOF

        if [[ $? -ne 0 ]]; then
            echo "No se pudo copiar la clave pública a $name. ¿Contraseña incorrecta o puerto/IP mal?"
            return 1
        fi
    fi
}

check_ssh_keys() {
    if [[ ! -f "$SSH_KEY_PATH" || ! -f "$SSH_KEY_PATH.pub" ]]; then
        echo "Claves SSH no encontradas, generando nuevas en $SSH_KEY_PATH"
        create_ssh_keys > /dev/null
    fi
}