#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

source $SCRIPT_DIR/params.conf

source $USER_CONF_FILE
source $SCRIPT_DIR/develop_getMachines > /dev/null

if  [[ $# -eq 1 ]]; then 
    name="$1"
    ip_port="${REMOTE_MACHINES[$name]}"

    ip="${ip_port%%:*}"
    port="${ip_port##*:}"

    # Comprobar si existe
    SESSION="$SESSIONS_PATH/${name}.vnc"

    if ! pgrep -f "ssh -i $SSH_KEY_PATH -f -N -p $port $USER@$ip" > /dev/null; then
        echo "Abriendo túnel SSH..."
        ssh -i "$SSH_KEY_PATH" -f -N -p "$port" "$USER@$ip"
    fi


    $TOOL $SESSION
else
    echo "Argumentos erroneos."
    echo ""
    echo "Uso: $0 [machine]"
fi
