#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

source $SCRIPT_DIR/params.conf

source $USER_CONF_FILE
source $SCRIPT_DIR/develop_getMachines > /dev/null

if  [[ $# -eq 1 ]]; then 
    name="$1"
    ip_port="${REMOTE_MACHINES[$name]}"

    ip="${ip_port%%:*}"
    port="${ip_port##*:}"

    # Comprobar si existe
    SESSION="./sessions/${name}_session.vnc"

    # Meter un try para probar varias formas de abrir SSH
    ssh -f -N -p $port $USER@$ip    # Se abre el tunnel en segundo plano (heckear que no cree multiples tuneles)
    echo "Tunnel SSH abierto"

    $VNC_VIEWER $SESSION            # Verificar que no es bloqueante
else
    echo "Argumentos erroneos."
    echo ""
    echo "Uso: $0 [machine]"
fi
